---
- hosts: all
  gather_facts: false
  remote_user: root
  tasks:
      - name: restarting buildbot_bridge_bblistener
        command: supervisorctl restart buildbot_bridge_bblistener
      - name: restarting buildbot_bridge_tclistener
        command: supervisorctl restart buildbot_bridge_tclistener
      - name: restarting buildbot_bridge_reflector
        command: supervisorctl restart buildbot_bridge_reflector

